- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    source_folder: './.ssh'
    dest_folder: "{{ lookup('env', 'HOME') }}/.ssh/"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"

  pre_tasks:
    - name: Update apt
      become: true
      apt:
        update_cache: true
        force_apt_get: true
        state: present
      tags:
        - install
        - core
  tasks:
     - include_tasks: tasks/setup-core.yml
     - include_tasks: tasks/setup-slack.yml
     - include_tasks: tasks/setup-zsh.yml
     - include_tasks: tasks/setup-node.yml
     - include_tasks: tasks/setup-personal.yml
     - include_tasks: tasks/setup-ssh.yml
     - name: Install JB toolbox
       become: true
       shell: chmod 755 ./install-jetbrains-toolbox.sh && ./install-jetbrains-toolbox.sh
       ignore_errors: yes
