- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    update_cache: true
    name:
      [
          "build-essential",
          "cmake",
          "pkg-config",
          "libpthread-stubs0-dev",
          "ca-certificates",
          "gnupg",
          "lsb-release",
          "software-properties-common",
          "apt-transport-https",
          "wget",
      ]
  tags:
    - install
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext" ]
  tags:
    - install
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name:
      [
          "curl",
          "htop",
          "jq",
          "lsof",
          "python3-pip",
          "dconf-editor",
          "pavucontrol",
          "moreutils",
          "bat",
      ]
  tags:
    - install
    - core

- name: Install lsd
  become: true
  apt:
    deb: https://github.com/Peltoche/lsd/releases/download/0.21.0/lsd_0.21.0_amd64.deb

- name: docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags:
    - install
    - core

- name: docker APT repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
  tags:
    - install
    - core

- name: VSCode gpg
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
  tags:
    - install
    - core

- name: VSCode repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  tags:
    - install
    - core

- name: Install VSCode
  become: true
  apt:
    name: code
    update_cache: true

- name: install docker
  become: true
  apt:
    name: docker-ce
    update_cache: true
  tags:
    - install
    - core
- name: install Fabric
  become: true
  pip:
    name: Fabric3
    executable: pip3

- name: install pexpect
  become: true
  pip:
    name: pexpect
    executable: pip3

- name: Insomnia
  apt:
    deb: https://updates.insomnia.rest/downloads/ubuntu/latest?&app=com.insomnia.app&source=website
  tags:
    - install
    - core

- name: Install Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  tags:
    - install
    - core

- name: Install lazydocker
  shell: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  tags:
    - install
    - core

- name: Install packages
  become: true
  apt:
    name:
      [
          "tmux",
          "fzf",
          "gimp",
          "xclip",
          "gnome-tweak-tool",
          "openvpn",
          "redis-server",
      ]
  tags:
    - install
    - productivity
